### ISSUE TITLE
Install error after latest changes (May 8th): Unexpected token line 110

### ISSUE THREAD

**Issue by JimAllen256** [danTapps/Hubitat#5]
When trying to install the latest version of the NTP client in Hubitat, getting an "unexpected token: else @ line 110, column 5." . Should the else in new line 108 actually be an else if {brackets enclosing the rest of line 108 through the end of line 111}?? I'm not familiar with the subtleties of Groovy syntax so please excuse if I'm off base here

**Comment by captain-coredump** [comment]
For what it's worth, I just encountered the same error trying to do a new install today...

**Comment by danTapps** [comment]
That was fixed today. Take the latest code and you should be good
